version: "3"

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  keycloak1:
    image: quay.io/keycloak/keycloak:24.0
    command:
      [
        "start",
        "--hostname=node1",
        "--optimized",
        "--http-enabled=true",
        "--verbose",
      ]
    # ["start", "--hostname=node1", "--cache=ispn", "--verbose"]
    # ["start", "--hostname=node1", "--cache=ispn", "--verbose"]

    environment:
      KC_DB: postgres
      # KC_DB_URL: "jdbc:postgresql://db/keycloak"
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      # KC_CACHE_REMOTE_HOST: cache:6379
      # KC_CACHE_REMOTE_PASSWORD: secret123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    # ports:
    #   - 8080:8080
    depends_on:
      - db

  keycloak2:
    image: quay.io/keycloak/keycloak:24.0
    command:
      [
        "start",
        "--hostname=node2",
        "--optimized",
        "--http-enabled=true",
        "--verbose",
      ]
    # ["start", "--hostname=node2", "--cache=ispn", "--verbose"]
    # ["start", "--hostname=node2", "--cache=ispn", "--verbose"]

    environment:
      KC_DB: postgres
      # KC_DB_URL: "jdbc:postgresql://db/keycloak"
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      # KC_CACHE_REMOTE_HOST: cache:6379
      # KC_CACHE_REMOTE_PASSWORD: secret123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    # ports:
    #   - 8081:8081
    depends_on:
      - db

  cache:
    image: redis:6.2.7
    command: redis-server --requirepass secret123
    ports:
      - 6379:6379

  haproxy:
    image: haproxy:2.6
    ports:
      - 8080:8080
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - keycloak1
      - keycloak2
